Quaternion Approach for impemention spatial rotations
===

**Overview of the notebook:**
    - Basic Library imports and variables
    - Printing
    - Intro to bits and bytes
    - Math in Python
    - Python modules closer
    - Python datatypes
    - If Then-constructs
    - Loops
    - Folder and File operations
    - Functions
    - Basics of nummeric python
    - Statistics review

In [2]:
import scripts.QuaternionTools as quad
import scripts.RotationMatrixTools as rotMat

import numpy as np
import math



#https://www.wallenborn.net/download/Vortrag-Sommerakademie-2012-Quaternionen.pdf
# https://github.com/moble/quaternion




In [2]:
#quad.Q_conj()

q1=quad.Q_make(90,np.array([0,0,1]))

#rotMat.Rypr()

In [3]:
q1

array([ 0.70710678,  0.        ,  0.        ,  0.70710678])

In [4]:
L2=30
qZ=quad.Q_normalize(quad.Q_make(360+L2,[0,0,1]))  # dreht um Z (R3) um Längengrad L
print(qZ)

[-0.96592583 -0.         -0.         -0.25881905]


# Der Punkt P(0, 2, 6) soll um 60° bzgl. der z-Achse rotiert werden. 

In [5]:
w=60
x=0
y=2
z=6

#Rotationsachse = Z-Achse
# --> Quaternion Imaginärteil [0,0,1]  is die Rotationachse um die gedreht wird

#Einheitsquaternion erstellen
q=np.array([ np.cos((60*math.pi)/(2*180)),0,0,-1*np.sin((60*math.pi)/(2*180)) ] )
print(q)

# Normieren des Quaternions
print( np.sqrt(np.dot(q,q)))

qE=q/np.sqrt(np.dot(q,q))
print( qE)

print("Prüfung: " , np.sqrt(np.dot(qE,qE)))


## Rotation des Vektors [0,2,6] um 60°
# Erweitern des Vektors auf 4.Dim, einfach 0 als erste Komponente hinzufügen
p=np.array([0,0,2,6])
print( p)
# inverse von qE bilden, ist gleich dem konjugierten weil Einheitsquaternion
iqE=-qE
iqE[0]=-iqE[0]
print (iqE)

#ausführen der Rotation als quaternionen Multiplikation
pr=quad.Q_mult(quad.Q_mult(qE,p),iqE)
print( pr)

pr=quad.Q_mult(qE,quad.Q_mult(p,iqE))
print(pr)

[ 0.8660254  0.         0.        -0.5      ]
1.0
[ 0.8660254  0.         0.        -0.5      ]
Prüfung:  1.0
[0 0 2 6]
[ 0.8660254 -0.        -0.         0.5      ]
[ 0.          1.73205081  1.          6.        ]
[ 0.          1.73205081  1.          6.        ]


# First Tests

In [6]:
q1=quad.Q_make(60,[0,0,5])
print (q1)
q2=quad.Q_conj(q1)
print( q2)
print( quad.Q_normalize(q2))

[ 0.8660254  0.         0.         2.5      ]
[ 0.8660254 -0.        -0.        -2.5      ]
[ 0.32732684 -0.         -0.         -0.94491118]


In [7]:

#makeQuat(60,[2,3,4])

qE=quad.Q_normalize(quad.Q_make(60,[0,0,-1]))
print("Prüfung: " , np.sqrt(np.dot(qE,qE)))

iQE=quad.Q_inv(qE)

quad.Q_rotateVector([0,0,-1],60,[0,2,6])

Prüfung:  1.0


array([ 1.73205081,  1.        ,  6.        ])

In [8]:
p=np.array([0,0,2,6])
pr=quad.Q_mult(quad.Q_mult(qE,p),iQE)
print( pr)

[ 0.          1.73205081  1.          6.        ]


In [9]:
arr=np.array([0,2,6])
np.append([0],arr)

array([0, 0, 2, 6])

In [10]:
q1=quad.Q_make(20,[0,3/np.sqrt(13),2/np.sqrt(13)])
print (q1)
q2=quad.Q_conj(q1)
print( q2)
print( quad.Q_normalize(q2))

[ 0.98480775  0.          0.14448402  0.09632268]
[ 0.98480775 -0.         -0.14448402 -0.09632268]
[ 0.98480775 -0.         -0.14448402 -0.09632268]


The vector $[2,3,4]$ is rotated 20° over the axis $\frac{1}{\sqrt{13}}[0,3,2]$

In [11]:
quad.Q_rotateVector([0,3/np.sqrt(13),2/np.sqrt(13)],20,[2,3,4])

array([ 2.44854116,  3.43510563,  3.34734155])

In [12]:
Q1=quad.Q_make(1,[2,3,4])

In [13]:
Q2=quad.Q_make(2,[4,6,8])

In [14]:
print(Q1)
print(Q2)

[ 0.99996192  0.01745307  0.02617961  0.03490614]
[ 0.9998477   0.06980963  0.10471444  0.13961925]


In [15]:
Q1+Q2

array([ 1.99980962,  0.0872627 ,  0.13089405,  0.17452539])

In [16]:
Q3=quad.Q_make(3,[6,9,12])
print(Q3)

[ 0.99965732  0.15706169  0.23559253  0.31412338]


In [17]:
qa=quad.Q_make(1,[0,1,1])
qb=quad.Q_make(1,[1,0,0])

In [18]:
q=quad.Q_mult(qa,qb)
print( q)

[ 0.99992385  0.0087262   0.00880236  0.00865005]


RotationsMatrix: 

In [19]:
Rq=rotMat.QtoR(q)
print(Rq)

[[ 0.99977154 -0.01714516  0.01775433]
 [ 0.01745241  0.99977421 -0.0172988 ]
 [-0.01745241  0.01760336  0.9997689 ]]


In [20]:
rotMat.Rypr(0,0,-90)

matrix([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   6.12323400e-17,   1.00000000e+00],
        [  0.00000000e+00,  -1.00000000e+00,   6.12323400e-17]])

In [21]:
print(np.cos(90*np.pi/180))
print( np.sin(90*np.pi/180))

6.12323399574e-17
1.0


In [22]:
z=quad.Q_make(0,[0,0,1])
print(z)

[ 1.  0.  0.  0.]


In [23]:
z3=rotMat.Rypr(0,0,90)*np.matrix([0,0,1]).T
print( z3)

[[  0.00000000e+00]
 [ -1.00000000e+00]
 [  6.12323400e-17]]


**Ein Einfaches Beispiel: rotiere den Einheitsvektor "z" um "x" mit einem Winkel von -90°  := "-y" 
**

In [24]:
x=[0,3./np.sqrt(13),2./np.sqrt(13)]
winkel=20*np.pi/180

q=quad.Q_make(winkel,x)
print(q)
print(np.cos(10*np.pi/180))
print(np.sin(10*np.pi/180))

[ 0.99999536  0.          0.00253457  0.00168971]
0.984807753012
0.173648177667


In [25]:
neuZ1=quad.Q_mult(q,z)
print( neuZ1)
neuZ2=quad.Q_mult(neuZ1,quad.Q_inv(q))
print( neuZ2)

[ 0.99999536  0.          0.00253457  0.00168971]
[ 1.  0.  0.  0.]


In [26]:
who

L2	 Q1	 Q2	 Q3	 Rq	 arr	 iQE	 iqE	 math	 
neuZ1	 neuZ2	 np	 p	 pr	 q	 q1	 q2	 qE	 
qZ	 qa	 qb	 quad	 rotMat	 w	 winkel	 x	 y	 
z	 z3	 


Rotate Vector $\vec a$ around Z-axis by 60°, right handed!
---

In [27]:
a=quad.Q_make(0,[1,2,0])
print(a)
z=quad.Q_make(60,[0,0,1])
print(z)


[ 1.  0.  0.  0.]
[ 0.8660254  0.         0.         0.5      ]


check the lenght of the vector before rotation:

In [28]:
print(np.dot([1.,2.,0.],[1.,2.,0.]))

5.0


Axis: z=[0,0,1] angle: $\frac{\alpha}{2}$= -30° because quad rotation is made always by the half angle element... the result is shown here: [2.23,0.14,0]

In [29]:
b=quad.Q_rotateVector([0,0,1],-60,[1,2,0])
print(b) 

[ 2.23205081  0.1339746   0.        ]


check the lenght of the vector after rotation:

In [30]:
print(np.dot(b,b))

5.0


proof the correct rotation by way over rotation matrix: result must be the same!

In [31]:
a=np.array([1,2,0])
R=rotMat.Rypr(60,0,0)
print(R)

[[ 0.5       -0.8660254  0.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]


In [32]:
print(np.dot(a,R))

[[ 2.23205081  0.1339746   0.        ]]


correct!

now generate the Rotation Matrix $R$ from the Quaternion 

In [33]:
print(rotMat.QtoR(z))

[[ 0.5       -0.8660254  0.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]


and it's also the same...

In [ ]:
a_z60_x30=quad.Q_mult(quad.Q_mult(x,a_z60),quad.Q_conj(x))


In [54]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np
from itertools import product, combinations
from matplotlib.patches import FancyArrowPatch
from mpl_toolkits.mplot3d import proj3d
%matplotlib notebook

fig = plt.figure()
ax = fig.gca(projection='3d')
ax.set_aspect("equal")

#draw cube
#r = [-1, 1]
#for s, e in combinations(np.array(list(product(r,r,r))), 2):
#    if np.sum(np.abs(s-e)) == r[1]-r[0]:
#        ax.plot3D(*zip(s,e), color="b")

#draw sphere
u, v = np.mgrid[0:2*np.pi:20j, 0:np.pi:10j]
r=10
x=r*np.cos(u)*np.sin(v)
y=r*np.sin(u)*np.sin(v)
z=r*np.cos(v)
ax.plot_wireframe(x, y, z, color="gray")

#draw a center point
ax.scatter([0],[0],[0],color="g",s=100)

#draw a vector
class Arrow3D(FancyArrowPatch):
    def __init__(self, xs, ys, zs, *args, **kwargs):
        FancyArrowPatch.__init__(self, (0,0), (0,0), *args, **kwargs)
        self._verts3d = xs, ys, zs

    def draw(self, renderer):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
        self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))
        FancyArrowPatch.draw(self, renderer)

e1 = Arrow3D([0,5],[0,0],[0,0], mutation_scale=20, lw=1, arrowstyle="-|>", color="r")
e2 = Arrow3D([0,0],[0,5],[0,0], mutation_scale=20, lw=1, arrowstyle="-|>", color="g")
e3 = Arrow3D([0,0],[0,0],[0,5], mutation_scale=20, lw=1, arrowstyle="-|>", color="b")

ax.add_artist(e3)
ax.add_artist(e2)
ax.add_artist(e1)


#plt.legend()
plt.show()

<IPython.core.display.Javascript object>

In [56]:
fig = plt.figure()
ax = fig.gca(projection='3d')
ax.set_aspect("equal")


e1 = Arrow3D([0,5],[0,0],[0,0], mutation_scale=20, lw=1, arrowstyle="-|>", color="r")
e2 = Arrow3D([0,0],[0,5],[0,0], mutation_scale=20, lw=1, arrowstyle="-|>", color="g")
e3 = Arrow3D([0,0],[0,0],[0,5], mutation_scale=20, lw=1, arrowstyle="-|>", color="b")

ax.add_artist(e3)
ax.add_artist(e2)
ax.add_artist(e1)


#plt.legend()
plt.show()

<IPython.core.display.Javascript object>

Now make 2 rotations after each other...

Rotate Vector $\vec a$ around Z-axis by 60°, right-handed! and around the X-axis bei 30°, also right-handed. 
---

In [42]:
a=np.array([0,1,2,0])
print(a)
z=quad.Q_normalize(quad.Q_make(-60,[0,0,1]))
print(z)
x=quad.Q_normalize(quad.Q_make(-30,[1,0,0]))
print(x)

[0 1 2 0]
[ 0.8660254 -0.        -0.        -0.5      ]
[ 0.96592583 -0.25881905 -0.         -0.        ]


First check if the general procedure works the same as the function **quad.Q_rotateVector()**

In [41]:
a_z60=quad.Q_mult(quad.Q_mult(z,a),quad.Q_conj(z))
print(a_z60[1:])

[ 2.23205081  0.1339746   0.        ]


In [44]:
a_z60_x30=quad.Q_mult(quad.Q_mult(x,a_z60),quad.Q_conj(x))
print(a_z60_x30[1:])

[ 2.23205081  0.1160254  -0.0669873 ]


The cool thing is now that if we multiply the two quaternion z(60°) and x(30°) to a new **quaternion zx** befor 

In [51]:
f=quad.Q_mult(x,z)

and than use this quaternion xz to rotate $\vec a$ we get the same result straight away in one step: 

In [53]:
af=quad.Q_mult(quad.Q_mult(f,a),quad.Q_conj(f))
print(af[1:])

[ 2.23205081  0.1160254  -0.0669873 ]


The results of quad.Q_rotateVector() for two following rotations are:

In [43]:
print(quad.Q_rotateVector([0,0,1],-60,[1,2,0]))
c=quad.Q_rotateVector([0,0,1],-60,[1,2,0])
d=quad.Q_rotateVector([1,0,0],-30,c)
print(d)

[ 2.23205081  0.1339746   0.        ]
[ 2.23205081  0.1160254  -0.0669873 ]


So the fazit is here that every possible rotion in space can be expressed in quaternions. Any rotation chain can be expressed as a chain of quaternion multiplications resulting in one final quaternion that summerizes the rotations

Try it yourself and add a third rotation to this chain...