In [9]:
import scripts.QuaternionTools as quad
import scripts.RotationMatrixTools as rotMat

import numpy as np
import math

In [10]:
#quad.Q_conj()

q1=quad.Q_make(90,np.array([0,0,1]))

#rotMat.Rypr()

In [11]:
q1

array([ 0.70710678,  0.        ,  0.        ,  0.70710678])

In [12]:
L2=30
qZ=quad.Q_normalize(quad.Q_make(360+L2,[0,0,1]))  # dreht um Z (R3) um Längengrad L
print(qZ)

[-0.96592583 -0.         -0.         -0.25881905]


# Der Punkt P(0, 2, 6) soll um 60° bzgl. der z-Achse rotiert werden. 

In [13]:
w=60
x=0
y=2
z=6

#Rotationsachse = Z-Achse
# --> Quaternion Imaginärteil [0,0,1]  is die Rotationachse um die gedreht wird

#Einheitsquaternion erstellen
q=np.array([ np.cos((60*math.pi)/(2*180)),0,0,-1*np.sin((60*math.pi)/(2*180)) ] )
print(q)

# Normieren des Quaternions
print( np.sqrt(np.dot(q,q)))

qE=q/np.sqrt(np.dot(q,q))
print( qE)

print("Prüfung: " , np.sqrt(np.dot(qE,qE)))


## Rotation des Vektors [0,2,6] um 60°
# Erweitern des Vektors auf 4.Dim, einfach 0 als erste Komponente hinzufügen
p=np.array([0,0,2,6])
print( p)
# inverse von qE bilden, ist gleich dem konjugierten weil Einheitsquaternion
iqE=-qE
iqE[0]=-iqE[0]
print (iqE)

#ausführen der Rotation als quaternionen Multiplikation
pr=quad.Q_mult(quad.Q_mult(qE,p),iqE)
print( pr)

pr=quad.Q_mult(qE,quad.Q_mult(p,iqE))
print(pr)

[ 0.8660254  0.         0.        -0.5      ]
1.0
[ 0.8660254  0.         0.        -0.5      ]
Prüfung:  1.0
[0 0 2 6]
[ 0.8660254 -0.        -0.         0.5      ]
[ 0.          1.73205081  1.          6.        ]
[ 0.          1.73205081  1.          6.        ]


# First Tests

In [14]:
q1=quad.Q_make(60,[0,0,5])
print (q1)
q2=quad.Q_conj(q1)
print( q2)
print( quad.Q_normalize(q2))

[ 0.8660254  0.         0.         2.5      ]
[ 0.8660254 -0.        -0.        -2.5      ]
[ 0.32732684 -0.         -0.         -0.94491118]


In [15]:

#makeQuat(60,[2,3,4])

qE=quad.Q_normalize(quad.Q_make(60,[0,0,-1]))
print("Prüfung: " , np.sqrt(np.dot(qE,qE)))

iQE=quad.Q_inv(qE)

quad.Q_rotateVector([0,0,-1],60,[0,2,6])

Prüfung:  1.0


array([ 1.73205081,  1.        ,  6.        ])

In [16]:
p=np.array([0,0,2,6])
pr=quad.Q_mult(quad.Q_mult(qE,p),iQE)
print( pr)

[ 0.          1.73205081  1.          6.        ]


In [17]:
arr=np.array([0,2,6])
np.append([0],arr)

array([0, 0, 2, 6])

In [18]:
q1=quad.Q_make(20,[0,3/np.sqrt(13),2/np.sqrt(13)])
print (q1)
q2=quad.Q_conj(q1)
print( q2)
print( quad.Q_normalize(q2))

[ 0.98480775  0.          0.14448402  0.09632268]
[ 0.98480775 -0.         -0.14448402 -0.09632268]
[ 0.98480775 -0.         -0.14448402 -0.09632268]


The vector $[2,3,4]$ is rotated 20° over the axis $\frac{1}{\sqrt{13}}[0,3,2]$

In [19]:
quad.Q_rotateVector([0,3/np.sqrt(13),2/np.sqrt(13)],20,[2,3,4])

array([ 2.44854116,  3.43510563,  3.34734155])

In [20]:
Q1=quad.Q_make(1,[2,3,4])

In [21]:
Q2=quad.Q_make(2,[4,6,8])

In [23]:
print(Q1)
print(Q2)

[ 0.99996192  0.01745307  0.02617961  0.03490614]
[ 0.9998477   0.06980963  0.10471444  0.13961925]


In [24]:
Q1+Q2

array([ 1.99980962,  0.0872627 ,  0.13089405,  0.17452539])

In [27]:
Q3=quad.Q_make(3,[6,9,12])
print(Q3)

[ 0.99965732  0.15706169  0.23559253  0.31412338]


In [28]:
qa=quad.Q_make(1,[0,1,1])
qb=quad.Q_make(1,[1,0,0])

In [29]:
q=quad.Q_mult(qa,qb)
print( q)

[ 0.99992385  0.0087262   0.00880236  0.00865005]


RotationsMatrix: 

In [32]:
Rq=rotMat.QtoR(q)
print(Rq)

[[ 0.99977154 -0.01714516  0.01775433]
 [ 0.01745241  0.99977421 -0.0172988 ]
 [-0.01745241  0.01760336  0.9997689 ]]


In [33]:
rotMat.Rypr(0,0,-90)

matrix([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   6.12323400e-17,   1.00000000e+00],
        [  0.00000000e+00,  -1.00000000e+00,   6.12323400e-17]])

In [34]:
print(np.cos(90*np.pi/180))
print( np.sin(90*np.pi/180))

6.12323399574e-17
1.0


In [46]:
z=quad.Q_make(0,[0,0,1])
print(z)

[ 1.  0.  0.  0.]


In [37]:
z3=rotMat.Rypr(0,0,90)*np.matrix([0,0,1]).T
print( z3)

[[  0.00000000e+00]
 [ -1.00000000e+00]
 [  6.12323400e-17]]


**Ein Einfaches Beispiel: rotiere den Einheitsvektor "z" um "x" mit einem Winkel von -90°  := "-y" 
**

In [38]:
x=[0,3./np.sqrt(13),2./np.sqrt(13)]
winkel=20*np.pi/180

q=quad.Q_make(winkel,x)
print(q)
print(np.cos(10*np.pi/180))
print(np.sin(10*np.pi/180))

[ 0.99999536  0.          0.00253457  0.00168971]
0.984807753012
0.173648177667


In [47]:
neuZ1=quad.Q_mult(q,z)
print( neuZ1)
neuZ2=quad.Q_mult(neuZ1,quad.Q_inv(q))
print( neuZ2)

[ 0.99999536  0.          0.00253457  0.00168971]
[ 1.  0.  0.  0.]


In [43]:
who

No variables match your requested type.
