Spatial Intersection in Photogrammetry
===

**Overview of the notebook:**
    - Reading the input files
    - making the observations vector
    - calculate observations from stereo view equations
    - make the Delta Vector between observations and calculated observations
    - generate A-Matrix
    - Adjustment Iterations

**Todos**
 - documentation of matrix structure and computing strategy
 - script rrws.py function calcDifferentials
 - compare results of python with old protocolls
 - 

In [4]:
###
import sys,math
import numpy as np
import pandas as pd
import scripts.rrws as RRWS
import scripts.RotationMatrixTools as rotMat

#as spin
# https://mail.python.org/pipermail/tutor/2004-November/033608.html 
    
    
    

In [2]:
#inputFile=pd.read_csv('figures/Beo.dat')

#print(inputFile)


In [3]:
#np.dot(PointMatIn[1,1:4],PointMatIn[1,1:4])

In [4]:
#PointMatIn[1,1]**2 +PointMatIn[1,2]**2+PointMatIn[1,3]**2

**reading input data**

In [7]:
#p1 = RRWS.Point(1,    1361.29,  -1402.17,       200,   0.110,   0.110)  
#p2 = RRWS.Point(2,    1038.53,    1026.25,      500,  -0.110,   0.110)
#p3 = RRWS.Point(3,   -1253.46,    1139.02,      300,  -0.110,  -0.110)
#p4 = RRWS.Point(4,   -1325.27,   -1421.83,      250,   0.110,  -0.110)
#pEO= RRWS.Point('EO',   1.132,      1.132, 2002.264,       0,       0)  
 

c=0.15  
x0IO=0.0     
y0IO=0.0
#1.132  1.132  2002.264    -2.0        1.0     -98.0

omegaEO=-2.0*np.pi/200.0          
phiEO=1.0*np.pi/200.0     
kappaEO=-98.0*np.pi/200.0


PointMatIn=np.zeros((6,23))
#print(PointMatIn)
PointMatIn[0,:]=[c,x0IO,y0IO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
PointMatIn[1,:]=[1,    1361.29,  -1402.17,       200,   0.110,   0.110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
PointMatIn[2,:]=[2,    1038.53,    1026.25,      500,  -0.110,   0.110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
PointMatIn[3,:]=[3,   -1253.46,    1139.02,      300,  -0.110,  -0.110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
PointMatIn[4,:]=[4,   -1325.27,   -1421.83,      250,   0.110,  -0.110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
PointMatIn[5,:]=[0,      1.132,      1.132, 2002.264,  omegaEO,  phiEO,kappaEO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]  

#print(PointMatIn)
#print('Input Array has Dims: {} '.format(PointMatIn.shape))
# rotMat.RyprG(   kappaEO     ,   phiEO       , omegaEO       )
#Ra =rotMat.RyprG(PointMatIn[5,6],PointMatIn[5,5],PointMatIn[5,4])
#print(Ra)
#print(20*"-")
#print(Rb)
#print(20*"=")



r=omegaEO
p=phiEO
y=kappaEO
print('sin(omega)=',math.sin(r))
print('cos(omega)=',math.cos(r))
print(20*"-")
print('sin(phi)=',math.sin(p))
print('cos(phi)=',math.cos(p))
print(20*"-")
print('sin(kappa)=',math.sin(y))
print('cos(kappa)=',math.cos(y))
print(20*"-")
Rr = np.array([[1.0, 0.0, 0.0],[0.0, math.cos(r), -math.sin(r)],[0.0, math.sin(r), math.cos(r)]])
Rp = np.matrix([[math.cos(p), 0.0, math.sin(p)],[0.0, 1.0, 0.0],[-math.sin(p), 0.0, math.cos(p)]])
Ry = np.matrix([[math.cos(y), -math.sin(y), 0.0],[math.sin(y), math.cos(y), 0.0],[0.0, 0.0, 1.0]])

print(20*"-")
print(Rr)
print(20*"-")
print(Rp)
print(20*"-")
print(Ry)
print(20*"-")
print(Ry*Rp*Rr) #ZYX-rotationsreihenfolge
print(20*"-")

r11= math.cos(phiEO)*math.cos(kappaEO);
r12=-math.cos(phiEO)*math.sin(kappaEO);
r13= math.sin(phiEO);

r21= math.cos(omegaEO)*math.sin(kappaEO)+math.sin(omegaEO)*math.sin(phiEO)*math.cos(kappaEO);
r22= math.cos(omegaEO)*math.cos(kappaEO)-math.sin(omegaEO)*math.sin(phiEO)*math.sin(kappaEO);
r23=-math.sin(omegaEO)*math.cos(phiEO);

r31= math.sin(omegaEO)*math.sin(kappaEO)-math.cos(omegaEO)*math.sin(phiEO)*math.cos(kappaEO);
r32= math.sin(omegaEO)*math.cos(kappaEO)+math.cos(omegaEO)*math.sin(phiEO)*math.sin(kappaEO);
r33= math.cos(omegaEO)*math.cos(phiEO);

print(r11,r12,r13)
print(r21,r22,r23)
print(r31,r32,r33)
print(20*"-")
R2=np.array([[r11,r12,r13],[r21,r22,r23],[r31,r32,r33]])
print(R2)




sin(omega)= -0.03141075907812829
cos(omega)= 0.9995065603657316
--------------------
sin(phi)= 0.015707317311820675
cos(phi)= 0.9998766324816606
--------------------
sin(kappa)= -0.9995065603657316
cos(kappa)= 0.031410759078128396
--------------------
--------------------
[[ 1.          0.          0.        ]
 [ 0.          0.99950656  0.03141076]
 [ 0.         -0.03141076  0.99950656]]
--------------------
[[ 0.99987663  0.          0.01570732]
 [ 0.          1.          0.        ]
 [-0.01570732  0.          0.99987663]]
--------------------
[[ 0.03141076  0.99950656  0.        ]
 [-0.99950656  0.03141076  0.        ]
 [ 0.          0.          1.        ]]
--------------------
[[ 0.03140688  0.99899787  0.0318884 ]
 [-0.99938325  0.0318884  -0.01470518]
 [-0.01570732 -0.03140688  0.99938325]]
--------------------
0.03140688401073177 0.9993832537218154 0.015707317311820675
-0.9990288616154956 0.030902124457446292 0.03140688401073167
0.030902124457446185 -0.01667845569632513 0.999383

In [8]:
Alger=RRWS.calcDifferentials(PointMatIn,R2)

print('===========================')
print(Alger)
#Storring all input data in a Matrix Structure

Input Array has Dims: (6, 23) 
calc deltas of Points
calc U, V and W
calc lger
calc A-Matrix x-equations
calc A-Matrix y-equations
[[  1.50000000e-01   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   1.36015800e+03  -1.40330200e+03  -1.80226400e+03
    1.10000000e-01   1.10000000e-01   1.38896374e+03   1.34601309e+03
   -1.82386137e+03   1.14232674e-01   1.10700280e-01  -3.56678504e-06
    8.01961373e-05  -6.51351806e-05   2.35938940e-01   9.17064896e-02
    1.10700280e-01  -3.53636363e-06   8.02569651e-05  -6.31996085e-05
    9.48975040e-02   2.24637479e-01  -1.14232674e-01]
 [  2.00000000e+00   1.03739800e+03   1.02511800e+03  -1.5022

In [9]:
print("%0.11f" % PointMatIn[1,11],  "%0.11f" %PointMatIn[1,12] , "%0.11f" %PointMatIn[1,13])

-0.00000356679 0.00008019614 -0.00006513518


In [10]:
PointMatIn[1:5,11:14]

array([[ -3.56678504e-06,   8.01961373e-05,  -6.51351806e-05],
       [ -2.08401501e-06,   1.05461935e-04,   7.05262024e-05],
       [ -1.77608649e-06,   9.09631152e-05,   6.21138091e-05],
       [ -3.53960741e-06,   8.05943216e-05,  -6.27689177e-05]])

**make observation vector**

In [11]:
lgem=np.zeros((8,1))
lgem[0:4,0]=Alger[1:5,4]
lgem[4:9,0]=Alger[1:5,5]

print(lgem)


[[ 0.11]
 [-0.11]
 [-0.11]
 [ 0.11]
 [ 0.11]
 [ 0.11]
 [-0.11]
 [-0.11]]


**calculate observations from stereo view equations**

In [12]:
lger=np.zeros((8,1))
lger[0:4,0]=Alger[1:5,9]
lger[4:9,0]=Alger[1:5,10]

print('===========================')
print(lger)

dl=lgem - lger
print(dl)

#https://support.pcigeomatics.com/hc/en-us/articles/203483349-Heading-Pitch-Roll-vs-Omega-Phi-Kappa

[[ 0.11423267]
 [-0.10716519]
 [-0.1093759 ]
 [ 0.10946501]
 [ 0.11070028]
 [ 0.11289819]
 [-0.10594671]
 [-0.11066703]]
[[-0.00423267]
 [-0.00283481]
 [-0.0006241 ]
 [ 0.00053499]
 [-0.00070028]
 [-0.00289819]
 [-0.00405329]
 [ 0.00066703]]


In [7]:
omegaEO=-2.0*math.pi/200.0          
phiEO=1.0*math.pi/200.0     
kappaEO=-98.0*math.pi/200.0

rotMat.RyprG(kappaEO,phiEO,omegaEO)


matrix([[ 0.03140688,  0.99899787,  0.0318884 ],
        [-0.99938325,  0.0318884 , -0.01470518],
        [-0.01570732, -0.03140688,  0.99938325]])

In [8]:
r=omegaEO
p=phiEO
y=kappaEO
Rr = np.matrix([[1.0, 0.0, 0.0],[0.0, math.cos(r), -math.sin(r)],[0.0, math.sin(r), math.cos(r)]])
Rp = np.matrix([[math.cos(p), 0.0, math.sin(p)],[0.0, 1.0, 0.0],[-math.sin(p), 0.0, math.cos(p)]])
Ry = np.matrix([[math.cos(y), -math.sin(y), 0.0],[math.sin(y), math.cos(y), 0.0],[0.0, 0.0, 1.0]])

R= np.dot(np.dot(Ry,Rp),Rr)

print(R)


[[ 0.03140688  0.99899787  0.0318884 ]
 [-0.99938325  0.0318884  -0.01470518]
 [-0.01570732 -0.03140688  0.99938325]]


In [11]:
delta = np.zeros((3,1))
print(delta[1])

[ 0.]


generate A-Matrix
===

In [13]:
A1=Alger[1:5,11:17]
A2=Alger[1:5,17:23]
A=np.concatenate(( A1,A2),axis=0)

print(A.shape)
np.set_printoptions(precision=8,suppress=True)
print(A)
#print in a better formated way

(8, 6)
[[-0.00000357  0.0000802  -0.00006514  0.23593894  0.09170649  0.11070028]
 [-0.00000208  0.00010546  0.00007053  0.23072935 -0.07350207  0.11289819]
 [-0.00000178  0.00009096  0.00006211  0.22552179  0.08443208 -0.10594671]
 [-0.00000354  0.00008059 -0.00006277  0.23054031 -0.07350044 -0.11066703]
 [-0.00000354  0.00008026 -0.0000632   0.0948975   0.22463748 -0.11423267]
 [-0.00000446  0.0001007  -0.00008085 -0.06122194  0.40781818  0.10716519]
 [-0.00000181  0.0000909   0.00006008  0.09279976  0.28459191  0.1093759 ]
 [-0.00000164  0.0000844   0.00005833 -0.07013756  0.22899687 -0.10946501]]


Cal Adjustment Interation
===

In [14]:
N=np.dot(A.T,A)
Qxx=np.linalg.inv(N)
dx=np.dot(Qxx,np.dot(A.T,dl))
print(dx)

[[-12288.        ]
 [  -512.        ]
 [   224.        ]
 [    -0.00970913]
 [    -0.00730498]
 [    -0.0138185 ]]


Update Unknowns
===

In [66]:
print(PointMatIn.shape)
PointMatUpdate=PointMatIn
print(PointMatUpdate.shape)
PointMatUpdate[5,:]=[0,      dx[0,0],      dx[1,0], dx[2,0],  dx[3,0],  dx[5,0],dx[5,0],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]  


(6, 23)
(6, 23)


In [67]:
print(dx[5,0])

0.0138185018571


In [16]:
R=rotMat.RyprG(PointMatUpdate[5,6],PointMatUpdate[5,5],PointMatUpdate[5,4])

Alger2=RRWS.calcDifferentials(PointMatUpdate,R)

print('===========================')
print(Alger2)


Input Array has Dims: (6, 23) 
calc deltas of Points
calc UVW
calc lger
calc A-Matrix x-equations
calc A-Matrix y-equations
[[  1.50000000e-01   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   9.55215800e+03  -1.03130200e+03  -2.01026400e+03
    1.10000000e-01   1.10000000e-01   9.55527931e+03  -1.17038043e+03
   -1.91711101e+03   7.47631144e-01  -9.15737603e-02  -7.95955227e-05
    2.12662251e-05  -3.89123473e-04   4.43319760e-01   3.87774507e+00
   -9.16539024e-02  -7.80760804e-05  -2.89411889e-06   4.79511940e-05
    7.65734282e+00  -4.57803268e-01  -7.48285444e-01]
 [  2.00000000e+00   9.22939800e+03   1.39711800e+03  -1.71026400e+0

In [17]:
A1=Alger2[1:5,11:17]
A2=Alger2[1:5,17:23]
A=np.concatenate(( A1,A2),axis=0)

print(A.shape)

(8, 6)


**make the Delta Vector between observations and calculated observations**

In [18]:
lger=np.zeros((8,1))
lger[0:4,0]=Alger2[1:5,9]
lger[4:9,0]=Alger2[1:5,10]

print('===========================')
print(lger)

dl=lger - lgem
print(dl)


[[ 0.74763114]
 [ 0.79073029]
 [ 0.52999714]
 [ 0.54935622]
 [-0.09157376]
 [ 0.10884975]
 [ 0.10530135]
 [-0.09429065]]
[[ 0.63763114]
 [ 0.90073029]
 [ 0.63999714]
 [ 0.43935622]
 [-0.20157376]
 [-0.00115025]
 [ 0.21530135]
 [ 0.01570935]]


In [19]:
N=np.dot(A.T,A)
Qxx=np.linalg.inv(N)
dx=np.dot(Qxx,np.dot(A.T,dl))
print(dx)

[[ -3.90400000e+03]
 [ -7.53664000e+05]
 [ -4.50560000e+04]
 [  5.03911598e-02]
 [ -1.41308375e-01]
 [  1.30878805e+00]]


In [20]:
print(dx[2,0])

-45056.0
