In [2]:
###
import sys
import numpy as np
import pandas as pd
import scripts.rrws as RRWS
import scripts.RotationMatrixTools as rotMat

#as spin
# https://mail.python.org/pipermail/tutor/2004-November/033608.html 
    
    
    

In [3]:
#


inputFile=pd.read_csv('figures/Beo.dat')

print(inputFile)


                                 c[m]  x0[m]   y0[m]
0                                  0.15  0.0     0.0
1            PNR X[m]     Y[m]    Z[m]   x[m]   y[m]
2         5 1361.29  -1402.17  200   0.110   0.110  
3           6 1337.27  -1019.37  210   0.080   0.110
4           7  977.48  -1029.61  205   0.080   0.080
5           8  999.37  -1421.83  190   0.110   0.080
6  X0[m]  Y0[m]   Z0[m]     omega[gon] phi[gon] k...
7  1.132  1.132  2002.264  -2.0          1.0     ...


**reading input data**

In [25]:
p1 = RRWS.Point(1,    1361.29,  -1402.17,       200,   0.110,   0.110)  
p2 = RRWS.Point(2,    1038.53,    1026.25,      500,  -0.110,   0.110)
p3 = RRWS.Point(3,   -1253.46,    1139.02,      300,  -0.110,  -0.110)
p4 = RRWS.Point(4,   -1325.27,   -1421.83,      250,   0.110,  -0.110)
pEO= RRWS.Point('EO',   1.132,      1.132, 2002.264,       0,       0)  
 

c=0.15  
x0IO=0.0     
y0IO=0.0
#1.132  1.132  2002.264    -2.0        1.0     -98.0

omegaEO=-2.0          
phiEO=1.0     
kappaEO=-98.0


PointMatIn=np.zeros((6,11))
print(PointMatIn)
PointMatIn[0,:]=[c,x0IO,y0IO,0,0,0,0,0,0,0,0]
PointMatIn[1,:]=[1,    1361.29,  -1402.17,       200,   0.110,   0.110,0,0,0,0,0]
PointMatIn[2,:]=[2,    1038.53,    1026.25,      500,  -0.110,   0.110,0,0,0,0,0]
PointMatIn[3,:]=[3,   -1253.46,    1139.02,      300,  -0.110,  -0.110,0,0,0,0,0]
PointMatIn[4,:]=[4,   -1325.27,   -1421.83,      250,   0.110,  -0.110,0,0,0,0,0]
PointMatIn[5,:]=[0,      1.132,      1.132, 2002.264,  omegaEO,  phiEO,kappaEO,0,0,0,0]  

print(PointMatIn)


print('calc deltas of Points')
PointMatIn[1,1:4]=PointMatIn[1,1:4]-PointMatIn[5,1:4]
PointMatIn[2,1:4]=PointMatIn[2,1:4]-PointMatIn[5,1:4]
PointMatIn[3,1:4]=PointMatIn[3,1:4]-PointMatIn[5,1:4]
PointMatIn[4,1:4]=PointMatIn[4,1:4]-PointMatIn[5,1:4]


print('===========================')
print(PointMatIn)

print('calc UVW')
R=rotMat.RyprG(kappaEO,phiEO,omegaEO).T


PointMatIn[1,6:9]=np.dot(R,PointMatIn[1,1:4])
PointMatIn[2,6:9]=np.dot(R,PointMatIn[2,1:4])
PointMatIn[3,6:9]=np.dot(R,PointMatIn[3,1:4])
PointMatIn[4,6:9]=np.dot(R,PointMatIn[4,1:4])


print('===========================')
print(PointMatIn)

print('calc lger')

PointMatIn[1,9:11]=[ PointMatIn[0,1] - PointMatIn[0,0]*PointMatIn[1,6]/PointMatIn[1,8], PointMatIn[0,2] - PointMatIn[0,0]*PointMatIn[1,7]/PointMatIn[1,8] ]
PointMatIn[2,9:11]=[ PointMatIn[0,1] - PointMatIn[0,0]*PointMatIn[2,6]/PointMatIn[2,8], PointMatIn[0,2] - PointMatIn[0,0]*PointMatIn[2,7]/PointMatIn[2,8] ]
PointMatIn[3,9:11]=[ PointMatIn[0,1] - PointMatIn[0,0]*PointMatIn[3,6]/PointMatIn[3,8], PointMatIn[0,2] - PointMatIn[0,0]*PointMatIn[3,7]/PointMatIn[3,8] ]
PointMatIn[4,9:11]=[ PointMatIn[0,1] - PointMatIn[0,0]*PointMatIn[4,6]/PointMatIn[4,8], PointMatIn[0,2] - PointMatIn[0,0]*PointMatIn[4,7]/PointMatIn[4,8] ]


print('===========================')
print(PointMatIn)




#Storring all input data in a Matrix Structure

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[  1.50000000e-01   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   1.36129000e+03  -1.40217000e+03   2.00000000e+02
    1.10000000e-01   1.10000000e-01   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   1.03853000e+03   1.02625000e+03   5.00000000e+02
   -1.10000000e-01   1.10000000e-01   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.00000000e+00  -1.25346000e+03   1.13902000e+03   3.00000000e+02
   -1.10000000e-01  -1.10000000e-01   0.00000000e+00   0.00000000

In [28]:
print(PointMatIn[1:5,9:11].ravel())

[ 0.1272316   0.11835373 -0.09791891  0.11287728 -0.09811273 -0.09928473
  0.11914576 -0.1113152 ]


In [5]:
1360.158 -1403.3020000000001 -1802.264
pEO.No

[[ 1473.46357578]
 [ 1370.64938835]
 [-1737.14339043]


'EO'

**make observation vector**

In [6]:
lgem=np.zeros((8,1))
print(lgem.shape)
lgem=np.array([[p1.xI],[p2.xI],[p3.xI],[p4.xI],[p1.yI],[p2.yI],[p3.yI],[p4.yI]   ])
print(lgem)


(8, 1)
[[ 0.11]
 [-0.11]
 [-0.11]
 [ 0.11]
 [ 0.11]
 [ 0.11]
 [-0.11]
 [-0.11]]


**calculate observations from stereo view equations**

In [7]:
rotMat.RyprG(kappaEO,phiEO,omegaEO).T
#https://support.pcigeomatics.com/hc/en-us/articles/203483349-Heading-Pitch-Roll-vs-Omega-Phi-Kappa

matrix([[ 0.03140688, -0.99938325, -0.01570732],
        [ 0.99899787,  0.0318884 , -0.03140688],
        [ 0.0318884 , -0.01470518,  0.99938325]])

In [8]:
rotMat.RyprG(kappaEO,phiEO,omegaEO)


matrix([[ 0.03140688,  0.99899787,  0.0318884 ],
        [-0.99938325,  0.0318884 , -0.01470518],
        [-0.01570732, -0.03140688,  0.99938325]])

In [9]:


deltaP1=RRWS.Point.subtr(p1,pEO)
RRWS.Point.println(deltaP1) 

#deltaP2=RRWS.Point.subtr(p2,pEO)
#deltaP3=RRWS.Point.subtr(p3,pEO)

print(p1.Xw,p1.Yw,p1.Zw)
print(pEO.Xw,pEO.Yw,pEO.Zw)

print(deltaP1.Xw,deltaP1.Yw,deltaP1.Zw)

delta = np.zeros((3,1))
delta[0]=deltaP1.Xw
delta[1]=deltaP1.Yw
delta[2]=deltaP1.Zw
print(delta)

#UVW=np.zeros((3,1))
R=rotMat.RyprG(kappaEO,phiEO,omegaEO).T
         
UVW=np.dot(R,delta)
print(UVW)

print(   x0IO - c*UVW[0]/UVW[2] )
print(   y0IO - c*UVW[1]/UVW[2] )


#U=1360.158*0.99938325 + (-1403.302*(-0.03140688))+ (-1802.264* ( -0.01570732))
#print(U)
 
#W= 1360.158*   0.0318884+ (-1403.302*  0.99899787)+(-1802.264*   0.03140688)
#print(W)
#print(c*U/W)

#print(deltaP2)
#print(deltaP3)
#RRWS.Point.println(p1)

#RRWS.Point.println(pEO)

lger=np.zeros((8,1))


#U= r11*dX[i]+r21*dY[i]+r31*dZ[i];


#V[i]= r12*dX[i]+r22*dY[i]+r32*dZ[i];

#W[i]= r13*dX[i]+r23*dY[i]+r33*dZ[i];

#lger[i][0]=    xo - c*U[i]/W[i];

#lger[i+anz][0]=yo - c*V[i]/W[i];

( 1, 1360.158,-1403.3020000000001, -1802.264, 0.11, 0.11)
1361.29 -1402.17 200
1.132 1.132 2002.264
1360.158 -1403.3020000000001 -1802.264
[[ 1360.158]
 [-1403.302]
 [-1802.264]]
[[ 1473.46357578]
 [ 1370.64938835]
 [-1737.14339043]]
[[ 0.1272316]]
[[ 0.11835373]]


In [10]:
delta = np.zeros((3,1))
print(delta[1])

[ 0.]


make A-Matrix
===

In [29]:
A=np.zeros((8,6))

In [30]:
A

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])