Spatial Intersection in Photogrammetry
===

**Overview of the notebook:**
    - Reading the input files
    - making the observations vector
    - calculate observations from stereo view equations
    - make the Delta Vector between observations and calculated observations
    - generate A-Matrix
    - Adjustment Iterations

**Todos**
 - documentation of matrix structure and computing strategy
 - script rrws.py function calcDifferentials
 - compare results of python with old protocolls
 - 

In [1]:
###
import sys,math
import numpy as np
import pandas as pd
import scripts.rrws as RRWS
import scripts.RotationMatrixTools as rotMat

#as spin
# https://mail.python.org/pipermail/tutor/2004-November/033608.html 
    
    
    

In [2]:
#inputFile=pd.read_csv('figures/Beo.dat')

#print(inputFile)


In [3]:
#np.dot(PointMatIn[1,1:4],PointMatIn[1,1:4])

In [4]:
#PointMatIn[1,1]**2 +PointMatIn[1,2]**2+PointMatIn[1,3]**2

**reading input data**

In [5]:
#p1 = RRWS.Point(1,    1361.29,  -1402.17,       200,   0.110,   0.110)  
#p2 = RRWS.Point(2,    1038.53,    1026.25,      500,  -0.110,   0.110)
#p3 = RRWS.Point(3,   -1253.46,    1139.02,      300,  -0.110,  -0.110)
#p4 = RRWS.Point(4,   -1325.27,   -1421.83,      250,   0.110,  -0.110)
#pEO= RRWS.Point('EO',   1.132,      1.132, 2002.264,       0,       0)  
 

c=0.15  
x0IO=0.0     
y0IO=0.0
#1.132  1.132  2002.264    -2.0        1.0     -98.0

omegaEO=-2.0*np.pi/200.0          
phiEO=1.0*np.pi/200.0     
kappaEO=-98.0*np.pi/200.0


PointMatIn=np.zeros((6,23))
print(PointMatIn)
PointMatIn[0,:]=[c,x0IO,y0IO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
PointMatIn[1,:]=[1,    1361.29,  -1402.17,       200,   0.110,   0.110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
PointMatIn[2,:]=[2,    1038.53,    1026.25,      500,  -0.110,   0.110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
PointMatIn[3,:]=[3,   -1253.46,    1139.02,      300,  -0.110,  -0.110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
PointMatIn[4,:]=[4,   -1325.27,   -1421.83,      250,   0.110,  -0.110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
PointMatIn[5,:]=[0,      1.132,      1.132, 2002.264,  omegaEO,  phiEO,kappaEO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]  

#print(PointMatIn)
#print('Input Array has Dims: {} '.format(PointMatIn.shape))
# rotMat.RyprG(   kappaEO     ,   phiEO       , omegaEO       )
R=rotMat.RyprG(PointMatIn[5,6],PointMatIn[5,5],PointMatIn[5,4])

Alger=RRWS.calcDifferentials(PointMatIn,R)

print('===========================')
print(Alger)
#Storring all input data in a Matrix Structure

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.]]
Input Array has Dims: (6, 23) 
calc deltas of Points
calc UVW
calc lger
calc A-Matrix x-equations
calc A-Matrix y-equations
[[  1.50000000e-01   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.0000000

In [6]:
print("%0.11f" % PointMatIn[1,11],  "%0.11f" %PointMatIn[1,12] , "%0.11f" %PointMatIn[1,13])

-0.00000504751 0.00008737244 -0.00007184038


In [7]:
PointMatIn[1:5,11:14]

array([[ -5.04750744e-06,   8.73724374e-05,  -7.18403762e-05],
       [ -1.07093798e-06,   1.00090651e-04,   6.75605211e-05],
       [ -9.00123225e-07,   8.44531368e-05,   5.71165802e-05],
       [ -4.80120432e-06,   8.55598446e-05,  -6.58462884e-05]])

**make observation vector**

In [8]:
lgem=np.zeros((8,1))
lgem[0:4,0]=Alger[1:5,4]
lgem[4:9,0]=Alger[1:5,5]

print(lgem)


[[ 0.11]
 [-0.11]
 [-0.11]
 [ 0.11]
 [ 0.11]
 [ 0.11]
 [-0.11]
 [-0.11]]


**calculate observations from stereo view equations**

In [9]:
lger=np.zeros((8,1))
lger[0:4,0]=Alger[1:5,9]
lger[4:9,0]=Alger[1:5,10]

print('===========================')
print(lger)

dl=lger - lgem
print(dl)

#https://support.pcigeomatics.com/hc/en-us/articles/203483349-Heading-Pitch-Roll-vs-Omega-Phi-Kappa

[[ 0.1272316 ]
 [-0.09791891]
 [-0.09811273]
 [ 0.11914576]
 [ 0.11835373]
 [ 0.11287728]
 [-0.09928473]
 [-0.1113152 ]]
[[ 0.0172316 ]
 [ 0.01208109]
 [ 0.01188727]
 [ 0.00914576]
 [ 0.00835373]
 [ 0.00287728]
 [ 0.01071527]
 [-0.0013152 ]]


In [5]:
omegaEO=-2.0*math.pi/200.0          
phiEO=1.0*math.pi/200.0     
kappaEO=-98.0*math.pi/200.0

rotMat.RyprG(kappaEO,phiEO,omegaEO)


matrix([[ 0.03140688,  0.99899787,  0.0318884 ],
        [-0.99938325,  0.0318884 , -0.01470518],
        [-0.01570732, -0.03140688,  0.99938325]])

In [4]:
r=omegaEO
p=phiEO
y=kappaEO
Rr = np.matrix([[1.0, 0.0, 0.0],[0.0, math.cos(r), -math.sin(r)],[0.0, math.sin(r), math.cos(r)]])
Rp = np.matrix([[math.cos(p), 0.0, math.sin(p)],[0.0, 1.0, 0.0],[-math.sin(p), 0.0, math.cos(p)]])
Ry = np.matrix([[math.cos(y), -math.sin(y), 0.0],[math.sin(y), math.cos(y), 0.0],[0.0, 0.0, 1.0]])

R= np.dot(np.dot(Ry,Rp),Rr)

print(R)


[[ 0.03140688  0.99899787  0.0318884 ]
 [-0.99938325  0.0318884  -0.01470518]
 [-0.01570732 -0.03140688  0.99938325]]


In [11]:
delta = np.zeros((3,1))
print(delta[1])

[ 0.]


generate A-Matrix
===

In [12]:
A1=Alger[1:5,11:17]
A2=Alger[1:5,17:23]
A=np.concatenate(( A1,A2),axis=0)

print(A.shape)

(8, 6)


Cal Adjustment Interation
===

In [13]:
N=np.dot(A.T,A)
Qxx=np.linalg.inv(N)
dx=np.dot(Qxx,np.dot(A.T,dl))
print(dx)

[[ -8.19200000e+03]
 [ -3.72000000e+02]
 [  2.08000000e+02]
 [  5.52320040e-02]
 [  2.96961109e-02]
 [  3.29426194e-03]]


Update Unknowns
===

In [14]:
print(PointMatIn.shape)
PointMatUpdate=PointMatIn
print(PointMatUpdate.shape)
PointMatUpdate[5,:]=[0,      dx[0,0],      dx[1,0], dx[2,0],  dx[3,0],  dx[5,0],dx[5,0],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]  


(6, 23)
(6, 23)


In [15]:
print(dx[5,0])

0.00329426193674


In [16]:
R=rotMat.RyprG(PointMatUpdate[5,6],PointMatUpdate[5,5],PointMatUpdate[5,4])

Alger2=RRWS.calcDifferentials(PointMatUpdate,R)

print('===========================')
print(Alger2)


Input Array has Dims: (6, 23) 
calc deltas of Points
calc UVW
calc lger
calc A-Matrix x-equations
calc A-Matrix y-equations
[[  1.50000000e-01   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   9.55215800e+03  -1.03130200e+03  -2.01026400e+03
    1.10000000e-01   1.10000000e-01   9.55527931e+03  -1.17038043e+03
   -1.91711101e+03   7.47631144e-01  -9.15737603e-02  -7.95955227e-05
    2.12662251e-05  -3.89123473e-04   4.43319760e-01   3.87774507e+00
   -9.16539024e-02  -7.80760804e-05  -2.89411889e-06   4.79511940e-05
    7.65734282e+00  -4.57803268e-01  -7.48285444e-01]
 [  2.00000000e+00   9.22939800e+03   1.39711800e+03  -1.71026400e+0

In [17]:
A1=Alger2[1:5,11:17]
A2=Alger2[1:5,17:23]
A=np.concatenate(( A1,A2),axis=0)

print(A.shape)

(8, 6)


**make the Delta Vector between observations and calculated observations**

In [18]:
lger=np.zeros((8,1))
lger[0:4,0]=Alger2[1:5,9]
lger[4:9,0]=Alger2[1:5,10]

print('===========================')
print(lger)

dl=lger - lgem
print(dl)


[[ 0.74763114]
 [ 0.79073029]
 [ 0.52999714]
 [ 0.54935622]
 [-0.09157376]
 [ 0.10884975]
 [ 0.10530135]
 [-0.09429065]]
[[ 0.63763114]
 [ 0.90073029]
 [ 0.63999714]
 [ 0.43935622]
 [-0.20157376]
 [-0.00115025]
 [ 0.21530135]
 [ 0.01570935]]


In [19]:
N=np.dot(A.T,A)
Qxx=np.linalg.inv(N)
dx=np.dot(Qxx,np.dot(A.T,dl))
print(dx)

[[ -3.90400000e+03]
 [ -7.53664000e+05]
 [ -4.50560000e+04]
 [  5.03911598e-02]
 [ -1.41308375e-01]
 [  1.30878805e+00]]


In [20]:
print(dx[2,0])

-45056.0
