-01-Basics-of-Python-Programming-and-Exercises © by A.Richter
------------------------------------------

**Sources: **
www.introtopython.org  and    http://www.scipy-lectures.org/   


But before we start with learning Python

you should know at least a bit how to use the Commandline CMD (Windows) or Terminal (Linux & Mac)

https://www.thomas-krenn.com/de/wiki/Cmd-Befehle_unter_Windows


1) How do start the Commandline/Terminal in Windows, Linux, macOS? 

2) How do you change to a folder?

3) How do you create a new txt file in the folder?

4) How do you start Jupyter in this folder? 

Basic Libray Imports
===

Basic Python Libraries or modules can be imported like this:

In [4]:
import sys,math 

In [8]:
import this
#import codecs
#print(this.s.decode('rot13'))
print(this.s)

Gur Mra bs Clguba, ol Gvz Crgref

Ornhgvshy vf orggre guna htyl.
Rkcyvpvg vf orggre guna vzcyvpvg.
Fvzcyr vf orggre guna pbzcyrk.
Pbzcyrk vf orggre guna pbzcyvpngrq.
Syng vf orggre guna arfgrq.
Fcnefr vf orggre guna qrafr.
Ernqnovyvgl pbhagf.
Fcrpvny pnfrf nera'g fcrpvny rabhtu gb oernx gur ehyrf.
Nygubhtu cenpgvpnyvgl orngf chevgl.
Reebef fubhyq arire cnff fvyragyl.
Hayrff rkcyvpvgyl fvyraprq.
Va gur snpr bs nzovthvgl, ershfr gur grzcgngvba gb thrff.
Gurer fubhyq or bar-- naq cersrenoyl bayl bar --boivbhf jnl gb qb vg.
Nygubhtu gung jnl znl abg or boivbhf ng svefg hayrff lbh'er Qhgpu.
Abj vf orggre guna arire.
Nygubhtu arire vf bsgra orggre guna *evtug* abj.
Vs gur vzcyrzragngvba vf uneq gb rkcynva, vg'f n onq vqrn.
Vs gur vzcyrzragngvba vf rnfl gb rkcynva, vg znl or n tbbq vqrn.
Anzrfcnprf ner bar ubaxvat terng vqrn -- yrg'f qb zber bs gubfr!


In [9]:
d = {}
for c in (65, 97):
    for i in range(26):
        d[chr(i+c)] = chr((i+13) % 26 + c)

print("".join([d.get(c, c) for c in this.s]))



The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


now Print out something in Python
===

Printing of an Expression or a variable is easily done in this way:

In [18]:
print("+-/*   Summe: {} ".format(100))

+-/*   Summe: 100 


**Intro to Bits and Bytes**
==

BIT = binary digit – englisch  in german „binäre Ziffer“ oder auch Binärziffer

one bit can have two conditions $0$ or $1$

1bit = $\begin{bmatrix}
0          \\
1        \end{bmatrix}$

In [13]:
print('Numbers can be used in form of binary system or the decimal system')
print(' ')
print('binary = decimal')
print('110001 =', 1*(2**5)+1*(2**4)+0*(2**3)+0*(2**2)+0*(2**1)+1*(2**0))

Numbers can be used in form of binary system or the decimal system
 
binary = decimal
110001 = 49


But how to calculate this:

In [17]:
x=1*(2**5)+1*(2**4)+0*(2**3)+0*(2**2)+0*(2**1)+1*(2**0)
print(x)

print('or') 

print(int('110001', 2))

49
or
49


1 Byte = 8 Bits
= $\begin{bmatrix}
0  & 0&0&0&0&0&0&0       \\
1  & 1&1&1&1&1&1&1     \end{bmatrix}$

so in general 8 options to decide for 1 or 0


In [2]:
print("10010101")
print(int('10010101', 2))

10010101
149


This means that the binary number: 10010101 represents the decimal number: 49

try it yourself...

A little bit of Math in Python
==

Check the Value of a Variable - compare it to another one

In [15]:
x=3

In [16]:
x==5

False

In [17]:
x==3

True

In [34]:
x=3
y=5
print(x+y)
print(x-y)
print(x*y)
print(x/y)

8
-2
15
0.6


Division of values in Python 3 is different compared to Python 2 --> Python-2 is using "Int" Python-3 always "Float"!!!

In [13]:
5/3

1.6666666666666667

In [14]:
5.0/3.0

1.6666666666666667

**Modules**

Everybody knows that 10 x 10 = 100

In [3]:
log10(100)

NameError: name 'log10' is not defined

this means the base python module library does not know the function log10()

the python math module is needed to calculate this

In [19]:
import math

In [20]:
math.log10(100)

2.0

In general Python is build modular, which means for special things look for the right module and simply import it...

A modular function is always called in the form: **math.log10(100)** = "**moduleName.functionName(parameters)**" 

try it yourself...

Datatypes
===

We will now have a look at basic Datentypes like integer ("**int**") and floating point numbers like "**float**" or "double" and of course characters like "**string**".

**Typ: Sting**

In [26]:
import sys
S="D:\BHT-BERLIN\nDaten\datei1.shp"
print(S)
print(type(S))
print("Size: {} Bytes".format(sys.getsizeof(S)))

D:\BHT-BERLIN
Daten\datei1.shp
<class 'str'>
Size: 79 Bytes


oh look What happened here? The String S was cut in the middle...but why???

the folder  **"\nDaten"**  has a problem, the **"\n"** is interpreteed as a line break!!! 

try ist yourself with a different folder...

better this way:

always use "/" instead of "\" to separate folders

In [24]:
S="D:/BHT-BERLIN/nDaten/datei1.shp"
print(S)

D:/BHT-BERLIN/nDaten/datei1.shp


or use a so called raw string format **r"... \ ... \ ..."**

In [25]:
S=r"D:\BHT-BERLIN\nDaten\datei1.shp"
print(S)

D:\BHT-BERLIN\nDaten\datei1.shp


In [22]:
y="BHT"
z="Berlin"
print(y+" - "+z)
print(15*"-")
print(y) 
print("Size: {} Bytes".format(sys.getsizeof(y)))
print(z) 
print("Size: {} Bytes".format(sys.getsizeof(z)))

BHT - Berlin
---------------
BHT
Size: 52 Bytes
Berlin
Size: 55 Bytes


**Tye: Int**

In [27]:
I=0
print(type(I))
print("Size:{} Bytes".format(sys.getsizeof(I)) )

<class 'int'>
Size:24 Bytes


In [31]:
I=1
print(type(I))
print("Size:{} Bytes".format(sys.getsizeof(I)) )

<class 'int'>
Size:28 Bytes


In [30]:
print("Size:{} Bytes".format(sys.getsizeof(2 ** 63)) )

Size:36 Bytes


**Tye: Float**

In [31]:
F=2.0
#x=6.45678987665454433345666
print(type(F))
print("Size:{} Bytes".format(sys.getsizeof(F)))

<class 'float'>
Size:24 Bytes


In [30]:
F=6.45678987665454433345666
print(type(F))
print("Size:{} Bytes".format(sys.getsizeof(F)))

<class 'float'>
Size:24 Bytes


==> Why are the sizes of INT and FLOAT different?

https://stackoverflow.com/questions/10365624/sys-getsizeofint-returns-an-unreasonably-large-value

https://stackoverflow.com/questions/29826523/python-float-precision-float

The Command "whos" is printing out the current use of variables in the RAM.
--

In [9]:
whos

Variable   Type      Data/Info
------------------------------
I          int       2
X          str       D:\BHT-BERLIN\nDaten\datei1.shp
math       module    <module 'math' from '/ana<...>h.cpython-36m-darwin.so'>
sys        module    <module 'sys' (built-in)>
this       module    <module 'this' from '/ana<...>a/lib/python3.6/this.py'>
x          float     6.456789876654544
y          str       BHT
z          str       Berlin


**In every computer language there are decision and loops ,the so called:** 

If-Then-Else Decision Constructions 
===

In Python this is used in this way: 

In [10]:
x=5

if x<0:
    print(x)
    print(2*x)
else:
    print(100-x)

95


Loop Constructions
==

while-Loop

In [11]:
x=0
while x<10:
    print(x)
    x=x+1

0
1
2
3
4
5
6
7
8
9


for-loop

In [12]:
for i in range(35,40):
    print(i)

35
36
37
38
39


In [37]:
for i in range(35,55,5):
    print(i)

35
40
45
50


The function **range(START,STOP,STEP)** provides a high flexibility in combination with the for-Loop

Be aware that the specified STOP Value is always evaluated at the index before it


Folder and File Operations 
===

To Search a Folder for a specific File Type, the following construction can be used:

In [43]:
# list a Folder with Tif + Tfw Files

import glob
Folder='figures/'
#Folder='../../_Data_ori_Tif/AOI2_small_6_Test/'
# https://docs.python.org/2/library/glob.html 
# http://stackoverflow.com/questions/3207219/how-to-list-all-files-of-a-directory-in-python

JPGs=glob.glob(Folder+"*.jpg")
PNGs=glob.glob(Folder+"*.png")

for j in JPGs:
    print(j)

print(25*'-') 
    
for p in PNGs:
    print(p)

figures/doug.jpg
figures/iris_setosa.jpg
figures/iris_versicolor.jpg
figures/iris_virginica.jpg
figures/petal_sepal.jpg
-------------------------
figures/FE_Class.png
figures/feynman.png
figures/ml-eng.png
figures/supervised_scikit_learn.png


Functions
---------

Functions are a great topic in Python3

Simply write the litteral "def" at the beginning of a line
followed by the name of the function "MyFunct()" 

In [44]:
def MyFunct(af,bf):
    cf=af+bf
    return cf

a=4
b=4
print("a =",a,"| b =",b)
print(2*"-------")
su=MyFunct(a,b)
print("Summe(a,b): {}".format(su))

a = 4 | b = 4
--------------
Summe(a,b): 8


In [48]:
# Functions: indent blocks with 4 spaces
def hello_world(name, times=3):
    print("Say",name*times)
 
hello_world("yes")

Say yesyesyes


Basics of Nummeric Python (numpy) and Scientific Python (scipy)
---------------------------

Many scientific problems can be described with algebraic expressions, or short in a Matrix Formalism 

numpy is a module for Matrix manipulations

In [50]:
import numpy as np

A simple 4x4 Matrix or an 4x4 Array in nummeric Python is initilized like this:

In [21]:
A=np.array([[2,4,3,7],[1,2,3,4],[-2,4,5,7],[4,3,7,9]])
print(A)

[[ 2  4  3  7]
 [ 1  2  3  4]
 [-2  4  5  7]
 [ 4  3  7  9]]


Calculate the sum of each column

In [22]:
b=np.sum(A, axis=0)
print(b)

[ 5 13 18 27]


Calculate the sum of each row

In [23]:
c=np.sum(A, axis=1)
print(c)

[16 10 14 23]


Pick an element from the Array by its index

In [24]:
d=A[2,1]
print(A)
print("  ") 
print('The Value at index [row=2,col=1] is: {} '.format(d))

print('Size of the Value (.itemsize): {} Bytes '.format(d.itemsize))
print('Size of the Value (.nbytes): {} Bytes '.format(d.nbytes))

[[ 2  4  3  7]
 [ 1  2  3  4]
 [-2  4  5  7]
 [ 4  3  7  9]]
  
The Value at index [row=2,col=1] is: 4 
Size of the Value (.itemsize): 8 Bytes 
Size of the Value (.nbytes): 8 Bytes 


Pick a row from the array and play with the index in different ways

In [26]:
print('Row one to end: all Rows')
print('-------------')
print(A[1,:])
print(' ')
print('All Rows with specific Index')
print('-------------')
print(A[1,0:4])
print(' ')
print('All without the 1st Row ')
print('-------------')
print(A[1,1:4])
print('-------------')

Row one to end: all Rows
-------------
[1 2 3 4]
 
All Rows with specific Index
-------------
[1 2 3 4]
 
All without the 1st Row 
-------------
[2 3 4]
-------------


Change the Array, **replace the second row**

In [27]:
print(A) 
A2=A
print(2*'---------')
A2[1,:]=[5,6,7,8]

print(A2)

[[ 2  4  3  7]
 [ 1  2  3  4]
 [-2  4  5  7]
 [ 4  3  7  9]]
------------------
[[ 2  4  3  7]
 [ 5  6  7  8]
 [-2  4  5  7]
 [ 4  3  7  9]]


Creating a **Vector** in diffenrent ways

In [29]:
e=np.arange(0,11)
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [32]:
f=np.arange(1,8.5,0.5)
print(f)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8. ]


Matrix multiplication

In [39]:
print(A," \t\n\n",A2) 

[[ 2  4  3  7]
 [ 5  6  7  8]
 [-2  4  5  7]
 [ 4  3  7  9]]  	

 [[ 2  4  3  7]
 [ 5  6  7  8]
 [-2  4  5  7]
 [ 4  3  7  9]]


In [33]:
np.dot(A,A2)

array([[ 46,  65,  98, 130],
       [ 58, 108, 148, 204],
       [ 34,  57,  96, 116],
       [ 45,  89, 131, 182]])

Element-wise multiplication

In [34]:
A*A2

array([[ 4, 16,  9, 49],
       [25, 36, 49, 64],
       [ 4, 16, 25, 49],
       [16,  9, 49, 81]])

Revision of Statistic-Tools
----

**Mean Value and Standarddeviation**

Generate a list of 20 random values,
around 50

In [103]:
x=50+10*np.random.randn(20,1)
print(x)

[[ 41.59482751]
 [ 59.43655008]
 [ 33.42469536]
 [ 40.5579171 ]
 [ 71.16557896]
 [ 27.10040817]
 [ 60.04444181]
 [ 58.30891218]
 [ 38.6730831 ]
 [ 52.00083727]
 [ 39.15168817]
 [ 31.5525942 ]
 [ 52.49034837]
 [ 36.63040418]
 [ 55.74190451]
 [ 55.30373652]
 [ 52.37174155]
 [ 57.31837229]
 [ 37.67475312]
 [ 50.15780303]]


**Calculte the Mean of the Values:**

$ \bar{X} =\frac{\sum\nolimits_{i=1}^{20} x_i}{20}$ the long and old-school way

In [104]:
Xmean=np.sum(x)/20

print(Xmean)

47.5350298735


or calculate it with a numpy function:

In [105]:
np.mean(x)

47.535029873541738

try it  yourself:

**Calculate the Standard Deviation of the Values:**

$ std = \sqrt{\frac{\sum\nolimits_{i=1}^{20}(x_i - \bar{X})^2}{20-1}}$

In [106]:
np.sqrt( np.sum((x-np.mean(x))**2)/19 ) 

11.679563299046686

In [107]:
np.std(x)

11.383830151298655

but how is numpy calculating here? Be carefull is you use the function and read the documentation first...!!! 

In [108]:
print(np.std(x,ddof=1) )

11.679563299


https://stackoverflow.com/questions/34050491/standard-deviation-in-numpy

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.std.html

ddof : int, optional

ddof means **D**elta **D**egrees **o**f **F**reedom. The divisor used in calculations is N - ddof, where N represents the number of elements. **By default ddof is zero.**


In [65]:
numbers=np.array([[6,7,8,9,10]])
print(numbers)

[[ 6  7  8  9 10]]


In [66]:
np.mean(numbers)

8.0

In [94]:
np.std(numbers,ddof=1)

1.5811388300841898

is called the proper calculated std, with n-1 degrees of freedom

In [95]:
np.std(numbers)

1.4142135623730951

is called a Maximum Likelihood estimation of the std

explaind with a very simple example, see source...

<img src="figures/std.jpg">

source: https://www.frustfrei-lernen.de/mathematik/standardabweichung-berechnen.html